// Code generated by gen-functions; DO NOT EDIT.

package slice

import (
	"github.com/genkami/dogs/classes/algebra"
	"github.com/genkami/dogs/classes/cmp"
	"github.com/genkami/dogs/types/iterator"
	"github.com/genkami/dogs/types/pair"
)

// Some packages are unused depending on -include CLI option.
// This prevents compile error when corresponding functions are not defined.
var _ = (algebra.Monoid[int])(nil)
var _ = (cmp.Ord[int])(nil)
var _ = (iterator.Iterator[int])(nil)
var _ = (*pair.Pair[int, int])(nil)

// Filter returns a collection that only returns elements that satisfies given predicate.
func Filter[T any](xs Slice[T], fn func(T) bool) Slice[T] {
	return FromIterator[T](iterator.Filter[T](xs.Iter(), fn))
}

// Find returns a first element in xs that satisfies the given predicate fn.
// It returns false as a second return value if no elements are found.
func Find[T any](xs Slice[T], fn func(T) bool) (T, bool) {
	return iterator.Find[T](xs.Iter(), fn)
}

// FindElem returns a first element in xs that equals to e in the sense of given Eq.
// It returns false as a second return value if no elements are found.
func FindElem[T any](eq cmp.Eq[T]) func(xs Slice[T], e T) (T, bool) {
	return func(xs Slice[T], e T) (T, bool) {
		return iterator.FindElem[T](eq)(xs.Iter(), e)
	}
}

// FindElemIndex returns a first index of an element in xs that equals to e in the sense of given Eq.
// It returns negative value if no elements are found.
func FindElemIndex[T any](eq cmp.Eq[T]) func(xs Slice[T], e T) int {
	return func(xs Slice[T], e T) int {
		return iterator.FindElemIndex[T](eq)(xs.Iter(), e)
	}
}

// FindIndex returns a first index of an element in xs that satisfies the given predicate fn.
// It returns negative value if no elements are found.
func FindIndex[T any](xs Slice[T], fn func(T) bool) int {
	return iterator.FindIndex[T](xs.Iter(), fn)
}

// Fold accumulates every element in a collection by applying fn.
func Fold[T any, U any](init T, xs Slice[U], fn func(T, U) T) T {
	return iterator.Fold[T, U](init, xs.Iter(), fn)
}

// ForEach applies fn to each element in xs.
func ForEach[T any](xs Slice[T], fn func(T)) {
	iterator.ForEach[T](xs.Iter(), fn)
}

// Map returns a collection that applies fn to each element of xs.
func Map[T, U any](xs Slice[T], fn func(T) U) Slice[U] {
	return FromIterator[U](iterator.Map[T, U](xs.Iter(), fn))
}

// Max returns the largest element with respect to the given Ord.
// It returns <zero value>, false if the collection is empty.
func Max[T any](ord cmp.Ord[T]) func(xs Slice[T]) (T, bool) {
	return func(xs Slice[T]) (T, bool) {
		return iterator.Max(ord)(xs.Iter())
	}
}

// MaxBy returns the smallest element with respect to the given function.
// It returns <zero value>, false if the collection is empty.
func MaxBy[T any](xs Slice[T], less func(T, T) bool) (T, bool) {
	return iterator.MaxBy(xs.Iter(), less)
}

// Min returns the smallest element with respect to the given Ord.
// It returns <zero value>, false if the collection is empty.
func Min[T any](ord cmp.Ord[T]) func(xs Slice[T]) (T, bool) {
	return func(xs Slice[T]) (T, bool) {
		return iterator.Min(ord)(xs.Iter())
	}
}

// MinBy returns the smallest element with respect to the given function.
// It returns <zero value>, false if the collection is empty.
func MinBy[T any](xs Slice[T], less func(T, T) bool) (T, bool) {
	return iterator.MinBy(xs.Iter(), less)
}

// Sum sums up all values in xs.
// It returns m.Empty() when xs is empty.
func Sum[T any](m algebra.Monoid[T]) func(xs Slice[T]) T {
	return func(xs Slice[T]) T {
		var s algebra.Semigroup[T] = m
		return SumWithInit[T](s)(m.Empty(), xs)
	}
}

// SumWithInit sums up init and all values in xs.
func SumWithInit[T any](s algebra.Semigroup[T]) func(init T, xs Slice[T]) T {
	return func(init T, xs Slice[T]) T {
		return Fold[T, T](init, xs, s.Combine)
	}
}

// Zip combines two collections into one that contains pairs of corresponding elements.
func Zip[T, U any](a Slice[T], b Slice[U]) Slice[pair.Pair[T, U]] {
	return FromIterator[pair.Pair[T, U]](iterator.Zip(a.Iter(), b.Iter()))
}
